{% set name = "nodejs-wheel" %}
{% set version = "22.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/njzjz/nodejs-wheel/archive/v{{ version }}.tar.gz
  sha256: 4d78cc947a94a70c0d38003708cb2c3fa656ac2b28c17c65dd713d7fcb3a7bde
  patches:
    - 0001-hack-ROOT_DIR.patch

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - SKBUILD_WHEEL_CMAKE=0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - scikit-build-core
    - setuptools_scm
  run:
    - python >={{ python_min }}
    # unpin nodejs, so downstream packages can control the version
    - nodejs

test:
  imports:
    - nodejs_wheel
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - python -m nodejs_wheel --version
    - pip check

about:
  home: https://github.com/njzjz/nodejs-wheel
  summary: 'Python wrapper for Node.js wheels'
  description: |
    On PyPI, nodejs-wheel is unoffical Node.js wheels;
    on conda-forge, only the Python wrapper is provided.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/njzjz/nodejs-wheel
  dev_url: https://github.com/njzjz/nodejs-wheel

extra:
  recipe-maintainers:
    - njzjz
